#服务端口号，微服务必备
server:
  port: 8001

#服务名称，微服务必备
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: goodtime
    password: haojianyu

mybatis:
  mapperLocations: classpath:mapper/*.xml                    #专门放置mapper的映射文件
  type-aliases-package: com.goodtime.springcloud.entities    # 所有Entity别名类所在包
